services:
  sonarr:
    image: linuxserver/sonarr
    networks:
      - download-sonarr
      - overseerr-sonarr
      - prowlarr-sonarr
      - recyclarr-sonarr
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/DS918:/DS918
      - /volume2/docker/sonarr/config:/config
    restart: unless-stopped
    environment:
      PGID: 100
      PUID: 1030

networks:
  download-sonarr:
    name: download-sonarr
  overseerr-sonarr:
    name: overseerr-sonarr
  prowlarr-sonarr:
    name: prowlarr-sonarr
  recyclarr-sonarr:
    name: recyclarr-sonarr
