services:
  teddit:
    image: teddit/teddit
    environment:
      DOMAIN: teddit.shraymonks.com
      USE_HELMET: true
      USE_HELMET_HSTS: true
      TRUST_PROXY: true
      REDIS_HOST: teddit-redis
    ports:
      - '127.0.0.1:8880:8080'
    networks:
      - teddit_net
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/about',
        ]
      interval: 1m
      timeout: 3s
    depends_on:
      - teddit-redis

  teddit-redis:
    image: redis:6.2.5-alpine
    command: redis-server
    environment:
      REDIS_REPLICATION_MODE: master
    networks:
      - teddit_net

networks:
  teddit_net:
