services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv
    network_mode: host
    restart: unless-stopped
    user: 1030:100
    volumes:
      - /volume2/docker/isponsorblocktv/config.json:/app/config.json
