services:
  qbittorrent:
    image: linuxserver/qbittorrent
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/DS918/Downloads:/DS918/Downloads
      - /volume2/docker/qbittorrent/config:/config
    environment:
      PGID: 100
      PUID: 1030
