services:
  overseerr:
    image: sctx/overseerr
    networks:
      - overseerr-radarr
      - overseerr-sonarr
    ports:
      - 5055:5055
    user: 1030:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/overseerr/config:/app/config
    restart: unless-stopped

networks:
  overseerr-radarr:
    name: overseerr-radarr
  overseerr-sonarr:
    name: overseerr-sonarr
