services:
  readarr:
    image: linuxserver/readarr:develop
    networks:
      - prowlarr-readarr
    ports:
      - 8787:8787
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/DS918:/DS918
      - /volume2/docker/readarr/config:/config
    environment:
      PGID: 100
      PUID: 1030

networks:
  prowlarr-readarr:
    name: prowlarr-readarr
    external: true
