services:
  prowlarr:
    image: linuxserver/prowlarr
    networks:
      - prowlarr-cross-seed
      - prowlarr-radarr
      - prowlarr-readarr
      - prowlarr-sonarr
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/prowlarr/config:/config
    environment:
      PGID: 100
      PUID: 1030

networks:
  prowlarr-cross-seed:
    name: prowlarr-cross-seed
  prowlarr-radarr:
    name: prowlarr-radarr
  prowlarr-readarr:
    name: prowlarr-readarr
  prowlarr-sonarr:
    name: prowlarr-sonarr
