services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    depends_on:
      - mealie-api
    environment:
      # Set Frontend ENV Variables Here
      API_URL: http://mealie-api:9000 #
    restart: unless-stopped
    ports:
      - '9925:3000' #
    volumes:
      - /volume2/docker/mealie/data:/app/data/ #

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    deploy:
      resources:
        limits:
          memory: 1000M #
    depends_on:
      - postgres
    volumes:
      - /volume2/docker/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: true
      PUID: 1030
      PGID: 100
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.shraymonks.com

      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - /volume2/docker/mealie/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
