services:
  recyclarr:
    image: recyclarr/recyclarr
    networks:
      - radarr-recyclarr
      - recyclarr-sonarr
    user: 1030:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/recyclarr/config:/config
    restart: unless-stopped

networks:
  radarr-recyclarr:
    name: radarr-recyclarr
  recyclarr-sonarr:
    name: recyclarr-sonarr
