services:
  radarr:
    image: linuxserver/radarr
    networks:
      - autobrr-radarr
      - overseerr-radarr
      - prowlarr-radarr
      - radarr-recyclarr
      - radarr-unmonitorr
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/DS918:/DS918
      - /volume2/docker/radarr/config:/config
    restart: unless-stopped
    environment:
      PGID: 100
      PUID: 1030

networks:
  autobrr-radarr:
    name: autobrr-radarr
  overseerr-radarr:
    name: overseerr-radarr
  prowlarr-radarr:
    name: prowlarr-radarr
    external: true
  radarr-recyclarr:
    name: radarr-recyclarr
  radarr-unmonitorr:
    name: radarr-unmonitorr
