services:
  radarr:
    image: linuxserver/radarr
    networks:
      - download-radarr
      - overseerr-radarr
      - prowlarr-radarr
      - radarr-recyclarr
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/DS918:/DS918
      - /volume2/docker/radarr/config:/config
    restart: unless-stopped
    environment:
      PGID: 100
      PUID: 1030

networks:
  download-radarr:
    name: download-radarr
  overseerr-radarr:
    name: overseerr-radarr
  prowlarr-radarr:
    name: prowlarr-radarr
  radarr-recyclarr:
    name: radarr-recyclarr
