services:
  home-assistant:
    image: homeassistant/home-assistant
    network_mode: host
    restart: unless-stopped
    user: 1030:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/home-assistant/config:/config
