services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - adguardhome
      - autobrr
      - changedetection.io
      - home-assistant
      - portainer-ce
      - recyclarr
      - syncthing
    environment:
      TZ: America/Los_Angeles
      WATCHTOWER_CLEANUP: true
