services:
  unmonitorr:
    image: shraymonks/unmonitorr
    networks:
      - radarr-unmonitorr
      - sonarr-unmonitorr
    ports:
      - 9797:9797
    user: 1030:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      PLEX_EVENTS: media.play,library.new
      RADARR_API_KEY: $RADARR_API_KEY
      RADARR_HOST: http://radarr:7878
      SONARR_API_KEY: $SONARR_API_KEY
      SONARR_HOST: http://sonarr:8989

networks:
  radarr-unmonitorr:
    name: radarr-unmonitorr
    external: true
  sonarr-unmonitorr:
    name: sonarr-unmonitorr
    external: true
