services:
  adguardhome:
    image: adguard/adguardhome
    network_mode: host
    restart: unless-stopped
    user: 1030:100
    volumes:
      - /volume2/docker/adguardhome/conf:/opt/adguardhome/conf
      - /volume2/docker/adguardhome/work:/opt/adguardhome/work
