services:
  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - /volume2/docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped
