services:
  autobrr:
    image: ghcr.io/autobrr/autobrr
    ports:
      - 7474:7474
    restart: unless-stopped
    user: 1030:100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/docker/autobrr/config:/config
